# Stage 1: Build stage
FROM php:8.2-apache AS build

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y zip git
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php && \
    php -r "unlink('composer-setup.php');" && \
    mv composer.phar /usr/local/bin/composer

COPY ./datos/composer.json .
RUN composer install

# Stage 2: Final stage
FROM php:8.2-apache

WORKDIR /var/www/html

COPY --from=build /var/www/html /var/www/html
COPY ./datos/.htaccess .

RUN a2enmod rewrite
RUN sed -i 's/DocumentRoot.*$/DocumentRoot \/var\/www\/html\/public/' /etc/apache2/sites-enabled/000-default.conf